### PR TITLE
2021.03.04

### PR DESCRIPTION
**Pull request by david-pulkowski**
Brought in upstream changes & alpha tested locally

### CODE REVIEW

**Comment by moop-moop** [comment]
Is this a straight up merge of the more recent version?
wondering if we could resolve the Commitlint fails....

**Comment by david-pulkowski** [comment]
@moop-moop Yes sir it was just a straight up bring in the upstream changes and merge into a release-branch.
How ever you want to approach it. Like all things, new workflows to deal with! :)

If you want; if thats the case; would an issue be best to create to try to fix said errors?

**Comment by david-pulkowski** [comment]
@moop-moop Im actually kinda confused at the error(s). It looks like its complaining about commit stuff that is in the remote uptodate branch & Im kinda running around in circles; if I am reading it correctly, it basically seems like it doenst like something about commit messages:

> You have commit messages with errors ⧗ input: Add You have commit messages with errors ⧗ input: Add server.apparmor state; rm unused dirs ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint ⧗ input: fix init.sls extend ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint ⧗ input: Fix two issues when using a salt_user (#163) This fixes https://github.com/saltstack-formulas/mysql-formula/issues/157 * Avoid failures on first run with a salt_user defined Add a dependency on sls: mysql.salt-user to ensure MySQL users (especially the salt_user) get created early enough - without that, parts of the first run will fail (but a second run works). ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlintstate; rm unused dirs ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint ⧗ input: fix init.sls extend ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint ⧗ input: Fix two issues when using a salt_user (#163) This fixes https://github.com/saltstack-formulas/mysql-formula/issues/157 * Avoid failures on first run with a salt_user defined Add a dependency on sls: mysql.salt-user to ensure MySQL users (especially the salt_user) get created early enough - without that, parts of the first run will fail (but a second run works). ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
>

**Comment by david-pulkowski** [comment]
@moop-moop I think, it was with these commits:
https://github.com/saltstack-formulas/mysql-formula/commit/bb8e64685c8dcffeff509dada6c13315ecc16c34
https://github.com/saltstack-formulas/mysql-formula/commit/fc056f2419a16f6c5baa511f2081a879f9b4c257
https://github.com/saltstack-formulas/mysql-formula/commit/7ec43ad3c92a20134dc3e1bb6fc3475923d1c80e

**Review by moop-moop — APPROVED** [review]
👍🏼

**Pull request merged**
